//! MSS Extractor - Parse Java Synthea output and compute joint distributions.
//!
//! This module analyzes large populations generated by Java Synthea to extract
//! the statistical fingerprint needed for high-speed generation.

// FHIR shape structs (Condition, MedicationRequest, Observation, Encounter, etc.)
// carry several fields that the extractor reads from JSON but does not currently
// propagate downstream (id, subject, clinical_status, encounter_class, ...).
// They are kept on the structs for round-trip shape fidelity — adding or removing
// them would change the JSON contract the extractor accepts. Allow the dead-code
// warnings on the module rather than tagging each field individually.
#![allow(dead_code)]

use std::fs::File;
use std::io::{BufRead, BufReader};
use std::path::Path;

use ahash::AHashMap;
use serde::Deserialize;

use crate::error::MssResult;
use crate::fingerprint::{
    ConditionStats, DemographicBucket, JointDemographics, MedicationStats, MssFingerprint,
    ObservationStats, ProcedureStats,
};

/// Extracts Minimally Sufficient Statistics from Java Synthea FHIR output.
pub struct MssExtractor {
    /// Accumulated demographic counts.
    demographics: AHashMap<DemographicBucket, u64>,

    /// Condition occurrence counts by demographic bucket.
    conditions: AHashMap<String, ConditionAccumulator>,

    /// Medication occurrence counts.
    medications: AHashMap<String, MedicationAccumulator>,

    /// Observation occurrence counts.
    observations: AHashMap<String, ObservationAccumulator>,

    /// Procedure occurrence counts.
    procedures: AHashMap<String, ProcedureAccumulator>,

    /// Code co-occurrence matrix (sparse).
    cooccurrence: AHashMap<(String, String), u64>,

    /// Total patients processed.
    total_patients: u64,

    /// Total encounters processed.
    total_encounters: u64,
}

/// Accumulator for condition statistics.
#[derive(Debug, Clone, Default)]
struct ConditionAccumulator {
    code: String,
    display: String,
    total_count: u64,
    by_age_bucket: AHashMap<String, u64>,
    by_gender: AHashMap<String, u64>,
    by_race: AHashMap<String, u64>,
    chronic: bool,
    onset_ages: Vec<u32>,
}

/// Accumulator for medication statistics.
#[derive(Debug, Clone, Default)]
struct MedicationAccumulator {
    code: String,
    display: String,
    total_count: u64,
    by_condition: AHashMap<String, u64>,
}

/// Accumulator for observation statistics.
#[derive(Debug, Clone, Default)]
struct ObservationAccumulator {
    code: String,
    system: String,
    display: String,
    total_count: u64,
    by_encounter_type: AHashMap<String, u64>,
}

/// Accumulator for procedure statistics.
#[derive(Debug, Clone, Default)]
struct ProcedureAccumulator {
    code: String,
    system: String,
    display: String,
    total_count: u64,
    by_condition: AHashMap<String, u64>,
}

/// Simplified FHIR Bundle for parsing.
#[derive(Debug, Deserialize)]
struct FhirBundle {
    entry: Vec<FhirEntry>,
}

#[derive(Debug, Deserialize)]
struct FhirEntry {
    resource: FhirResource,
}

#[derive(Debug, Deserialize)]
#[serde(tag = "resourceType")]
enum FhirResource {
    Patient(PatientResource),
    Condition(ConditionResource),
    MedicationRequest(MedicationResource),
    Observation(ObservationResource),
    Procedure(ProcedureResource),
    Encounter(EncounterResource),
    #[serde(other)]
    Other,
}

#[derive(Debug, Deserialize)]
struct PatientResource {
    id: String,
    #[serde(rename = "birthDate")]
    birth_date: Option<String>,
    gender: Option<String>,
    #[serde(default)]
    extension: Vec<Extension>,
}

#[derive(Debug, Deserialize)]
struct Extension {
    url: String,
    #[serde(rename = "valueCoding")]
    value_coding: Option<ValueCoding>,
    #[serde(rename = "valueString")]
    value_string: Option<String>,
}

#[derive(Debug, Deserialize)]
struct ValueCoding {
    code: Option<String>,
    display: Option<String>,
}

#[derive(Debug, Deserialize)]
struct ConditionResource {
    id: String,
    code: Option<CodeableConcept>,
    subject: Option<Reference>,
    #[serde(rename = "onsetDateTime")]
    onset_date_time: Option<String>,
    #[serde(rename = "clinicalStatus")]
    clinical_status: Option<CodeableConcept>,
}

#[derive(Debug, Deserialize)]
struct MedicationResource {
    id: String,
    #[serde(rename = "medicationCodeableConcept")]
    medication_codeable_concept: Option<CodeableConcept>,
    subject: Option<Reference>,
    #[serde(rename = "reasonReference")]
    reason_reference: Option<Vec<Reference>>,
}

#[derive(Debug, Deserialize)]
struct ObservationResource {
    id: String,
    code: Option<CodeableConcept>,
    subject: Option<Reference>,
    category: Option<Vec<CodeableConcept>>,
}

#[derive(Debug, Deserialize)]
struct ProcedureResource {
    id: String,
    code: Option<CodeableConcept>,
    subject: Option<Reference>,
    #[serde(rename = "reasonReference")]
    reason_reference: Option<Vec<Reference>>,
}

#[derive(Debug, Deserialize)]
struct EncounterResource {
    id: String,
    #[serde(rename = "class")]
    encounter_class: Option<Coding>,
    subject: Option<Reference>,
}

#[derive(Debug, Deserialize)]
struct CodeableConcept {
    coding: Option<Vec<Coding>>,
    text: Option<String>,
}

#[derive(Debug, Deserialize)]
struct Coding {
    system: Option<String>,
    code: Option<String>,
    display: Option<String>,
}

#[derive(Debug, Deserialize)]
struct Reference {
    reference: Option<String>,
}

impl MssExtractor {
    /// Creates a new MSS extractor.
    pub fn new() -> Self {
        Self {
            demographics: AHashMap::new(),
            conditions: AHashMap::new(),
            medications: AHashMap::new(),
            observations: AHashMap::new(),
            procedures: AHashMap::new(),
            cooccurrence: AHashMap::new(),
            total_patients: 0,
            total_encounters: 0,
        }
    }

    /// Processes a directory of FHIR bundles (one JSON file per patient).
    pub fn process_fhir_directory<P: AsRef<Path>>(&mut self, dir: P) -> MssResult<()> {
        let entries = std::fs::read_dir(dir)?;

        for entry in entries {
            let entry = entry?;
            let path = entry.path();

            if path.extension().map_or(false, |ext| ext == "json") {
                self.process_fhir_bundle(&path)?;
            }
        }

        Ok(())
    }

    /// Processes NDJSON (newline-delimited JSON) file with FHIR bundles.
    pub fn process_ndjson<P: AsRef<Path>>(&mut self, path: P) -> MssResult<()> {
        let file = File::open(path)?;
        let reader = BufReader::new(file);

        for line in reader.lines() {
            let line = line?;
            if line.trim().is_empty() {
                continue;
            }

            match serde_json::from_str::<FhirBundle>(&line) {
                Ok(bundle) => self.process_bundle(&bundle)?,
                Err(e) => {
                    // Try parsing as individual resource
                    if let Ok(resource) = serde_json::from_str::<FhirResource>(&line) {
                        self.process_resource(&resource, None)?;
                    } else {
                        eprintln!("Warning: Failed to parse line: {}", e);
                    }
                }
            }
        }

        Ok(())
    }

    /// Processes a single FHIR bundle file.
    pub fn process_fhir_bundle<P: AsRef<Path>>(&mut self, path: P) -> MssResult<()> {
        let file = File::open(path)?;
        let reader = BufReader::new(file);
        let bundle: FhirBundle = serde_json::from_reader(reader)?;

        self.process_bundle(&bundle)
    }

    /// Processes a FHIR bundle.
    fn process_bundle(&mut self, bundle: &FhirBundle) -> MssResult<()> {
        // First pass: extract patient demographics
        let mut patient_info: Option<(String, DemographicBucket)> = None;
        let mut patient_conditions: Vec<String> = Vec::new();

        for entry in &bundle.entry {
            if let FhirResource::Patient(patient) = &entry.resource {
                patient_info = Some((patient.id.clone(), self.extract_demographics(patient)));
                self.total_patients += 1;
            }
        }

        let (_patient_id, demo_bucket) = match patient_info {
            Some(info) => info,
            None => return Ok(()), // No patient in bundle
        };

        // Count demographic occurrence
        *self.demographics.entry(demo_bucket.clone()).or_insert(0) += 1;

        // Second pass: process all resources
        for entry in &bundle.entry {
            self.process_resource(&entry.resource, Some(&demo_bucket))?;

            // Track conditions for co-occurrence
            if let FhirResource::Condition(cond) = &entry.resource {
                if let Some(code) = cond
                    .code
                    .as_ref()
                    .and_then(|c| c.coding.as_ref())
                    .and_then(|c| c.first())
                    .and_then(|c| c.code.clone())
                {
                    patient_conditions.push(code);
                }
            }
        }

        // Record condition co-occurrences
        for i in 0..patient_conditions.len() {
            for j in (i + 1)..patient_conditions.len() {
                let key = if patient_conditions[i] < patient_conditions[j] {
                    (patient_conditions[i].clone(), patient_conditions[j].clone())
                } else {
                    (patient_conditions[j].clone(), patient_conditions[i].clone())
                };
                *self.cooccurrence.entry(key).or_insert(0) += 1;
            }
        }

        Ok(())
    }

    /// Processes a single FHIR resource.
    fn process_resource(
        &mut self,
        resource: &FhirResource,
        demo_bucket: Option<&DemographicBucket>,
    ) -> MssResult<()> {
        match resource {
            FhirResource::Condition(cond) => {
                self.process_condition(cond, demo_bucket);
            }
            FhirResource::MedicationRequest(med) => {
                self.process_medication(med);
            }
            FhirResource::Observation(obs) => {
                self.process_observation(obs);
            }
            FhirResource::Procedure(proc) => {
                self.process_procedure(proc);
            }
            FhirResource::Encounter(_) => {
                self.total_encounters += 1;
            }
            _ => {}
        }
        Ok(())
    }

    /// Extracts demographics from a Patient resource.
    fn extract_demographics(&self, patient: &PatientResource) -> DemographicBucket {
        let age_bucket = patient
            .birth_date
            .as_ref()
            .and_then(|bd| self.calculate_age_bucket(bd))
            .unwrap_or_else(|| "18-44".to_string());

        let gender = patient
            .gender
            .clone()
            .unwrap_or_else(|| "unknown".to_string());

        let mut race = "white".to_string();
        let mut ethnicity = "nonhispanic".to_string();

        for ext in &patient.extension {
            if ext.url.contains("us-core-race") {
                if let Some(coding) = &ext.value_coding {
                    if let Some(code) = &coding.code {
                        race = self.map_race_code(code);
                    }
                }
            } else if ext.url.contains("us-core-ethnicity") {
                if let Some(coding) = &ext.value_coding {
                    if let Some(code) = &coding.code {
                        ethnicity = self.map_ethnicity_code(code);
                    }
                }
            }
        }

        DemographicBucket {
            age_bucket,
            gender,
            race,
            ethnicity,
        }
    }

    /// Calculates age bucket from birth date string.
    fn calculate_age_bucket(&self, birth_date: &str) -> Option<String> {
        let birth_year: i32 = birth_date.split('-').next()?.parse().ok()?;
        let current_year = 2024; // Reference year
        let age = current_year - birth_year;

        Some(match age {
            0..=17 => "0-17".to_string(),
            18..=44 => "18-44".to_string(),
            45..=64 => "45-64".to_string(),
            _ => "65+".to_string(),
        })
    }

    /// Maps race code to normalized string.
    fn map_race_code(&self, code: &str) -> String {
        match code {
            "2106-3" => "white".to_string(),
            "2054-5" => "black".to_string(),
            "2028-9" => "asian".to_string(),
            "1002-5" => "native".to_string(),
            _ => "other".to_string(),
        }
    }

    /// Maps ethnicity code to normalized string.
    fn map_ethnicity_code(&self, code: &str) -> String {
        match code {
            "2135-2" => "hispanic".to_string(),
            "2186-5" => "nonhispanic".to_string(),
            _ => "unknown".to_string(),
        }
    }

    /// Processes a Condition resource.
    fn process_condition(&mut self, cond: &ConditionResource, demo: Option<&DemographicBucket>) {
        let coding = match cond
            .code
            .as_ref()
            .and_then(|c| c.coding.as_ref())
            .and_then(|c| c.first())
        {
            Some(c) => c,
            None => return,
        };

        let code = match &coding.code {
            Some(c) => c.clone(),
            None => return,
        };

        // Check if chronic before borrowing self.conditions mutably
        let is_chronic = self.is_chronic_condition(&code);
        let display = coding.display.clone().unwrap_or_default();

        let acc = self
            .conditions
            .entry(code.clone())
            .or_insert_with(|| ConditionAccumulator {
                code: code.clone(),
                display,
                chronic: is_chronic,
                ..Default::default()
            });

        acc.total_count += 1;

        if let Some(demo) = demo {
            *acc.by_age_bucket
                .entry(demo.age_bucket.clone())
                .or_insert(0) += 1;
            *acc.by_gender.entry(demo.gender.clone()).or_insert(0) += 1;
            *acc.by_race.entry(demo.race.clone()).or_insert(0) += 1;
        }

        // Extract onset age if available
        if let Some(onset) = &cond.onset_date_time {
            if let Some(year) = onset.split('-').next().and_then(|y| y.parse::<i32>().ok()) {
                // Approximate onset age
                acc.onset_ages.push((2024 - year).max(0) as u32);
            }
        }
    }

    /// Determines if a condition is chronic based on code.
    fn is_chronic_condition(&self, code: &str) -> bool {
        // Common chronic condition codes
        const CHRONIC_CODES: &[&str] = &[
            "38341003",  // Hypertension
            "44054006",  // Diabetes type 2
            "195967001", // Asthma
            "53741008",  // CAD
            "73211009",  // Diabetes type 1
            "40930008",  // COPD
            "13644009",  // Hypercholesterolemia
        ];
        CHRONIC_CODES.contains(&code)
    }

    /// Processes a MedicationRequest resource.
    fn process_medication(&mut self, med: &MedicationResource) {
        let coding = match med
            .medication_codeable_concept
            .as_ref()
            .and_then(|c| c.coding.as_ref())
            .and_then(|c| c.first())
        {
            Some(c) => c,
            None => return,
        };

        let code = match &coding.code {
            Some(c) => c.clone(),
            None => return,
        };

        let acc = self
            .medications
            .entry(code.clone())
            .or_insert_with(|| MedicationAccumulator {
                code: code.clone(),
                display: coding.display.clone().unwrap_or_default(),
                ..Default::default()
            });

        acc.total_count += 1;

        // Track reason/indication
        if let Some(reasons) = &med.reason_reference {
            for reason in reasons {
                if let Some(ref_str) = &reason.reference {
                    // Extract condition ID from reference
                    if let Some(cond_id) = ref_str.strip_prefix("Condition/") {
                        *acc.by_condition.entry(cond_id.to_string()).or_insert(0) += 1;
                    }
                }
            }
        }
    }

    /// Processes an Observation resource.
    fn process_observation(&mut self, obs: &ObservationResource) {
        let coding = match obs
            .code
            .as_ref()
            .and_then(|c| c.coding.as_ref())
            .and_then(|c| c.first())
        {
            Some(c) => c,
            None => return,
        };

        let code = match &coding.code {
            Some(c) => c.clone(),
            None => return,
        };

        let acc = self
            .observations
            .entry(code.clone())
            .or_insert_with(|| ObservationAccumulator {
                code: code.clone(),
                system: coding.system.clone().unwrap_or_else(|| "LOINC".to_string()),
                display: coding.display.clone().unwrap_or_default(),
                ..Default::default()
            });

        acc.total_count += 1;
    }

    /// Processes a Procedure resource.
    fn process_procedure(&mut self, proc: &ProcedureResource) {
        let coding = match proc
            .code
            .as_ref()
            .and_then(|c| c.coding.as_ref())
            .and_then(|c| c.first())
        {
            Some(c) => c,
            None => return,
        };

        let code = match &coding.code {
            Some(c) => c.clone(),
            None => return,
        };

        let acc = self
            .procedures
            .entry(code.clone())
            .or_insert_with(|| ProcedureAccumulator {
                code: code.clone(),
                system: coding
                    .system
                    .clone()
                    .unwrap_or_else(|| "SNOMED-CT".to_string()),
                display: coding.display.clone().unwrap_or_default(),
                ..Default::default()
            });

        acc.total_count += 1;

        // Track indication
        if let Some(reasons) = &proc.reason_reference {
            for reason in reasons {
                if let Some(ref_str) = &reason.reference {
                    if let Some(cond_id) = ref_str.strip_prefix("Condition/") {
                        *acc.by_condition.entry(cond_id.to_string()).or_insert(0) += 1;
                    }
                }
            }
        }
    }

    /// Builds the MSS fingerprint from accumulated statistics.
    pub fn build_fingerprint(&self) -> MssFingerprint {
        let total_patients = self.total_patients as f64;

        // Build joint demographics distribution
        let joint_demographics = JointDemographics {
            buckets: self
                .demographics
                .iter()
                .map(|(bucket, count)| (bucket.clone(), *count as f64 / total_patients))
                .collect(),
            total_patients: self.total_patients,
        };

        // Build condition statistics
        let conditions: Vec<ConditionStats> = self
            .conditions
            .values()
            .map(|acc| {
                let prevalence = acc.total_count as f64 / total_patients;
                ConditionStats {
                    code: acc.code.clone(),
                    display: acc.display.clone(),
                    prevalence,
                    by_age_bucket: acc
                        .by_age_bucket
                        .iter()
                        .map(|(k, v)| (k.clone(), *v as f64 / acc.total_count.max(1) as f64))
                        .collect(),
                    by_gender: acc
                        .by_gender
                        .iter()
                        .map(|(k, v)| (k.clone(), *v as f64 / acc.total_count.max(1) as f64))
                        .collect(),
                    by_race: acc
                        .by_race
                        .iter()
                        .map(|(k, v)| (k.clone(), *v as f64 / acc.total_count.max(1) as f64))
                        .collect(),
                    chronic: acc.chronic,
                    mean_onset_age: if acc.onset_ages.is_empty() {
                        40.0
                    } else {
                        acc.onset_ages.iter().map(|&a| a as f64).sum::<f64>()
                            / acc.onset_ages.len() as f64
                    },
                }
            })
            .collect();

        // Build medication statistics. `by_condition` already carries the
        // empirical `P(reason | medication)` counts, so we emit a parallel
        // `indication_weights` vector — same length as `indications`, in the
        // same order — for the multi-cause REASONCODE sampler.
        let medications: Vec<MedicationStats> = self
            .medications
            .values()
            .map(|acc| {
                let total: u64 = acc.by_condition.values().sum();
                let mut pairs: Vec<(String, u64)> = acc
                    .by_condition
                    .iter()
                    .map(|(k, v)| (k.clone(), *v))
                    .collect();
                // Stable order so indications/indication_weights stay aligned.
                pairs.sort_by(|a, b| b.1.cmp(&a.1).then_with(|| a.0.cmp(&b.0)));
                let indications: Vec<String> = pairs.iter().map(|(c, _)| c.clone()).collect();
                let indication_weights: Vec<f64> = if total > 0 {
                    pairs.iter().map(|(_, n)| *n as f64 / total as f64).collect()
                } else {
                    vec![]
                };
                MedicationStats {
                    code: acc.code.clone(),
                    display: acc.display.clone(),
                    frequency: acc.total_count as f64 / self.total_encounters.max(1) as f64,
                    indications,
                    indication_weights,
                }
            })
            .collect();

        // Build observation statistics
        let observations: Vec<ObservationStats> = self
            .observations
            .values()
            .map(|acc| ObservationStats {
                code: acc.code.clone(),
                system: acc.system.clone(),
                display: acc.display.clone(),
                frequency: acc.total_count as f64 / self.total_encounters.max(1) as f64,
            })
            .collect();

        // Build procedure statistics (see medications above for the
        // by_condition → indications/indication_weights mapping).
        let procedures: Vec<ProcedureStats> = self
            .procedures
            .values()
            .map(|acc| {
                let total: u64 = acc.by_condition.values().sum();
                let mut pairs: Vec<(String, u64)> = acc
                    .by_condition
                    .iter()
                    .map(|(k, v)| (k.clone(), *v))
                    .collect();
                pairs.sort_by(|a, b| b.1.cmp(&a.1).then_with(|| a.0.cmp(&b.0)));
                let indications: Vec<String> = pairs.iter().map(|(c, _)| c.clone()).collect();
                let indication_weights: Vec<f64> = if total > 0 {
                    pairs.iter().map(|(_, n)| *n as f64 / total as f64).collect()
                } else {
                    vec![]
                };
                ProcedureStats {
                    code: acc.code.clone(),
                    system: acc.system.clone(),
                    display: acc.display.clone(),
                    frequency: acc.total_count as f64 / self.total_encounters.max(1) as f64,
                    indications,
                    indication_weights,
                }
            })
            .collect();

        // Build co-occurrence matrix (top pairs only for efficiency)
        let mut cooccurrence: Vec<((String, String), f64)> = self
            .cooccurrence
            .iter()
            .map(|(k, v)| (k.clone(), *v as f64 / total_patients))
            .collect();
        cooccurrence.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap());
        cooccurrence.truncate(1000); // Keep top 1000 pairs

        MssFingerprint {
            version: "1.0".to_string(),
            source: "java-synthea".to_string(),
            total_patients: self.total_patients,
            total_encounters: self.total_encounters,
            joint_demographics,
            conditions,
            medications,
            observations,
            procedures,
            cooccurrence: cooccurrence.into_iter().collect(),
            cooccurrence_dependent_scale: std::collections::BTreeMap::new(),
            onset_stats: Vec::new(),
            encounter_stats: Default::default(),
        }
    }

    /// Returns the number of patients processed.
    pub fn patients_processed(&self) -> u64 {
        self.total_patients
    }

    /// Returns the number of unique conditions found.
    pub fn unique_conditions(&self) -> usize {
        self.conditions.len()
    }
}

impl Default for MssExtractor {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_age_bucket_calculation() {
        let extractor = MssExtractor::new();

        assert_eq!(
            extractor.calculate_age_bucket("2020-01-01"),
            Some("0-17".to_string())
        );
        assert_eq!(
            extractor.calculate_age_bucket("2000-06-15"),
            Some("18-44".to_string())
        );
        assert_eq!(
            extractor.calculate_age_bucket("1970-03-20"),
            Some("45-64".to_string())
        );
        assert_eq!(
            extractor.calculate_age_bucket("1950-12-25"),
            Some("65+".to_string())
        );
    }

    #[test]
    fn test_race_mapping() {
        let extractor = MssExtractor::new();

        assert_eq!(extractor.map_race_code("2106-3"), "white");
        assert_eq!(extractor.map_race_code("2054-5"), "black");
        assert_eq!(extractor.map_race_code("2028-9"), "asian");
        assert_eq!(extractor.map_race_code("unknown"), "other");
    }

    #[test]
    fn test_empty_fingerprint() {
        let extractor = MssExtractor::new();
        let fp = extractor.build_fingerprint();

        assert_eq!(fp.total_patients, 0);
        assert!(fp.conditions.is_empty());
    }
}
